### ISSUE TITLE
Thank you a lot

### ISSUE THREAD

**Issue by michalss** [xobed/CsfdAPI#1]
This helped me a lot for my project. Can you also please make combination with imbd as well ? Is there any limitation for api calls to csfd servers ?

**Comment by michalss** [comment]
BTW found an issue with czech diacritics. in seach..

**Comment by michalss** [comment]
Also missing series category. Like for example https://www.csfd.cz/film/265160-vetrelci-davnoveku/686441-serie-2/diskuze/

**Comment by xobed** [comment]
Hi @michalss 
> This helped me a lot for my project. Can you also please make combination with imbd as well ?

For IMDB, I would recommend using their official datasets:
https://www.imdb.com/interfaces/

>  Is there any limitation for api calls to csfd servers ?

I did not encounter any rate limiting when using this library, however I only tested getting ~200-300 movies once per hour.

> BTW found an issue with special characters in query. Add this function to replace it with space..

What query are you using, what are the results you are getting, and what are the expected results?

> Also missing series category. Like for example https://www.csfd.cz/film/265160-vetrelci-davnoveku/686441-serie-2/diskuze/

This is what I am getting for this URL with `csfdApi.GetMovie("https://www.csfd.cz/film/265160-vetrelci-davnoveku/686441-serie-2/");`:
```
{
    "Genres": [
        "Dokumentární",
        "Historický",
        "Mysteriózní"
    ],
    "Plot": "",
    "PosterUrl": null,
    "Rating": 78,
    "Url": "https://www.csfd.cz/film/265160-vetrelci-davnoveku/686441-serie-2/",
    "Title": "Vetřelci dávnověku - Série 2 (série)",
    "Year": "2010"
}
```
What are you missing?

**Comment by michalss** [comment]
what i ment is to get list of series links. like this:

![image](https://user-images.githubusercontent.com/1000729/80497191-67d87880-896a-11ea-934f-674e7d8b8093.png)

**Comment by michalss** [comment]
about the spec. chars it was my mistake mostly. IF you gonna use special char in search sting it will throw an exception.. # / ( etc..

**Comment by xobed** [comment]
I will add this when I have some free time.
Also feel free to submit a pull request with this functionality.

**Comment by michalss** [comment]
Also 1 question do you think it is possible to scrape whole csfd somehow ?

**Comment by xobed** [comment]
> about the spec. chars it was my mistake mostly. IF you gonna use special char in search sting it will throw an exception.. # / ( etc..

Can you show me the code that throws the exception?
This works OK for me (On .NET Core 3.1):
```C#
var api = new CsfdApi();
var result = api.SearchMovie("12 let v řetězech");
```

**Comment by michalss** [comment]
`Vetřelci-dávnověku-(Ancient-aliens)---S02E02---Gods-and-Aliens-(Bohove-a-mimozemstane).avi`

**Comment by xobed** [comment]
> `Vetřelci-dávnověku-(Ancient-aliens)---S02E02---Gods-and-Aliens-(Bohove-a-mimozemstane).avi`

This works as expected.
Exception is `Failed to find movie with query: ...` - CSFD does not return anything so an exception is thrown
https://www.csfd.cz/hledat/?q=Vet%C5%99elci-d%C3%A1vnov%C4%9Bku-%28Ancient-aliens%29---S02E02---Gods-and-Aliens-%28Bohove-a-mimozemstane%29.avi

**Comment by xobed** [comment]
> Also 1 question do you think it is possible to scrape whole csfd somehow ?

You should be able to create a complete copy of CSFD database by using `ŽEBŘÍČKY`
https://www.csfd.cz/zebricky/specificky-vyber/?type=0&origin=&genre=1&year_from=2019&year_to=2019&actor=&director=&ok=Zobrazit&_form_=charts&show=complete
CSFD limits this to max 300 movies but if you filter by year and by genre, you can get all available movies / series.
Then repeat for all years you want to get

This is not currently implemented in this project.

**Comment by michalss** [comment]
Can this function can be also implementen "rebricky" pls ?

**Comment by xobed** [comment]
Created https://github.com/xobed/CsfdAPI/issues/2
I will add it later when I have more time

**Comment by xobed** [comment]
Closing this one, please open new issues if you need anything specific
