### ISSUE TITLE
Always single result

### ISSUE THREAD

**Issue by michalss** [xobed/CsfdAPI#6]
Hi during the search it always return single result, but this is wrong it should return Movie array with all results from csfd.

**Comment by xobed** [comment]
Added `csfdApi.SearchMovies` method

Example here:
https://github.com/xobed/CsfdAPI/blob/master/Example/Program.cs#L20

You can pass URLs to `csfdApi.GetMovie` to get `Movie` objects

**Comment by michalss** [comment]
nice thx
